services:
  tip-generator:
    image: suphra_recommendation_generator:local
    container_name: tip-generator
    ports:
      - "8050:8050"
    environment:
      - DATABASE_URL=mariadb+mariadbconnector://root:rootpw@mariadb:3306/copy_fellmann
    depends_on:
      mariadb:
        condition: service_started
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: copy_fellmann
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadb_data: 