name: tip_generator
channels:
  - conda-forge
dependencies:
  - python=3.11.10
  - mariadb-connector-c
  - gcc_linux-64  # Needed for compiling C extensions
  - gxx_linux-64  # C++ Compiler
  - make  # Needed for compilation
  - pathlib
  - pandas
  - litellm
  - python-dotenv
  - pip
  - pdf2image
  - pytesseract
  - matplotlib
  - scikit-learn
  - scipy
  - dash
  - plotly
  - loguru
  - hdbscan
  - sqlalchemy
  - pip:
    - mariadb>=1.1.12
    - getpaper
    - just-agents
    - sentence-transformers