name: tip_generator
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - gcc_linux-64  # LINUX (Needed for compiling C extensions)
  - gxx_linux-64  # LINUX (C++ Compiler)
  - mariadb=1.1.12
  - make  # Needed for compilation
  - pathlib
  - pandas
  - numpy=2.2.4
  - litellm
  - python-dotenv
  - matplotlib
  - scikit-learn
  - einops
  - transformers=4.51.1
  - sentence-transformers=4.0.2
  - scipy
  - dash
  - plotly
  - loguru
  - hdbscan
  - sqlalchemy
  - typer
  - fastapi
  - pip:
    - torch>=2.6.0
    - unstructured[pdf]
    - pdfminer.six==20240706
    - semanticscholar